export const moroccanCities = [
  'Agadir',
  'Ahfir',
  'Ain Aouda',
  'Ain Harrouda',
  'Ain Taoujdate',
  'Ait Melloul',
  'Al Hoceima',
  'Arfoud',
  'Assilah',
  'Azemmour',
  'Azilal',
  'Azrou',
  'Beni Mellal',
  'Benslimane',
  'Berkane',
  'Berrechid',
  'Biougra',
  'Bouarfa',
  'Boujdour',
  'Bouznika',
  'Casablanca',
  'Chefchaouen',
  'Chichaoua',
  'Dakhla',
  'Demnate',
  'El Aioun Sidi Mellouk',
  'El Hajeb',
  'El Jadida',
  'Errachidia',
  'Essaouira',
  'Fes',
  'Figuig',
  'Fnideq',
  'Fquih Ben Salah',
  'Guelmim',
  'Guercif',
  'Ifrane',
  'Imzouren',
  'Jerada',
  'Kelaat Sraghna',
  'Kenitra',
  'Khemisset',
  'Khenifra',
  'Khouribga',
  'Ksar El Kebir',
  'Laayoune',
  'Larache',
  'Marrakech',
  'Martil',
  'Mdiq',
  'Meknes',
  'Midelt',
  'Mohammedia',
  'Nador',
  'Ouarzazate',
  'Oued Zem',
  'Oujda',
  'Rabat',
  'Safi',
  'Sale',
  'Sefrou',
  'Settat',
  'Sidi Bennour',
  'Sidi Ifni',
  'Sidi Kacem',
  'Sidi Slimane',
  'Skhirat',
  'Souk El Arbaa',
  'Tan-Tan',
  'Tanger',
  'Taounate',
  'Taourirt',
  'Taroudant',
  'Taza',
  'Temara',
  'Tetouan',
  'Tiflet',
  'Tinghir',
  'Tiznit',
  'Youssoufia',
  'Zagora',
]

export function getMoroccanCities() {
  return moroccanCities
}
