import { useEffect } from 'react'
import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export const languages = [
  { id: 'en', label: 'English' },
  { id: 'fr', label: 'Francais' },
  { id: 'ar', label: 'العربية' },
]

export const messages = {
  en: {
    informationForm: 'Information form',
    ticketHistory: 'Ticket history',
    newTicket: 'New ticket',
    settings: 'Settings',
    supportTitle: 'PBxcom support',
    supportText: 'Review your requests or open a new support ticket.',
    clientInfoEyebrow: 'Client information',
    clientInfoTitle: 'Create a new ticket',
    clientInfoDescription:
      'Your previous client information is suggested below. You can edit any field before sending the new ticket.',
    firstTicketTitle: 'Complete your first ticket',
    firstTicketDescription: 'Fill in all client columns once. After that, your saved information will be locked for future tickets.',
    lockedClientFields: 'These details come from your account and are locked for this ticket.',
    savedClientFields: 'We filled these fields from your last ticket. You can customize them before sending.',
    chooseCity: 'Choose city',
    backToHistory: 'Back to history',
    nom: 'Nom',
    prenom: 'Prenom',
    societes: 'Societes',
    nMarche: 'N marche',
    nFacture: 'N facture',
    telephone: 'N telephone',
    mail: 'Mail',
    ville: 'Ville',
    problemDescription: 'Problem description',
    problemDescriptionPlaceholder: 'Describe your problem here with as much detail as you need.',
    submitInformation: 'Submit information',
    required: 'Required',
    invalidEmail: 'Use a valid email',
    invalidPhone: 'Use a valid phone number',
    fixFields: 'Please fix the highlighted fields.',
    sentInfo: 'Information sent to PBxcom.',
    reference: 'Reference',
    settingsEyebrow: 'Client settings',
    settingsTitle: 'Account settings',
    settingsDescription: 'Update your account information, password, and preferred language.',
    profileCard: 'Profile information',
    fullName: 'Full name',
    company: 'Company',
    email: 'Email',
    passwordCard: 'Security code',
    newPassword: 'New code / password',
    leaveBlank: 'Leave blank to keep the current code.',
    languageCard: 'Language',
    preferredLanguage: 'Preferred language',
    saveSettings: 'Save settings',
    settingsSaved: 'Settings updated successfully.',
  },
  fr: {
    informationForm: 'Formulaire',
    ticketHistory: 'Historique',
    newTicket: 'Nouveau ticket',
    settings: 'Parametres',
    supportTitle: 'Support PBxcom',
    supportText: 'Consultez vos demandes ou creez un nouveau ticket.',
    clientInfoEyebrow: 'Informations client',
    clientInfoTitle: 'Creer un nouveau ticket',
    clientInfoDescription:
      'Vos dernieres informations client sont proposees ci-dessous. Vous pouvez modifier chaque champ avant l envoi.',
    firstTicketTitle: 'Completez votre premier ticket',
    firstTicketDescription: 'Remplissez toutes les colonnes client une seule fois. Ensuite, vos informations seront bloquees pour les prochains tickets.',
    lockedClientFields: 'Ces informations viennent de votre compte et sont bloquees pour ce ticket.',
    savedClientFields: 'Ces champs sont repris depuis votre dernier ticket. Vous pouvez les modifier avant l envoi.',
    chooseCity: 'Choisir une ville',
    backToHistory: 'Retour a l historique',
    nom: 'Nom',
    prenom: 'Prenom',
    societes: 'Societes',
    nMarche: 'N marche',
    nFacture: 'N facture',
    telephone: 'N telephone',
    mail: 'Mail',
    ville: 'Ville',
    problemDescription: 'Description du probleme',
    problemDescriptionPlaceholder: 'Decrivez votre probleme ici avec tous les details necessaires.',
    submitInformation: 'Envoyer les informations',
    required: 'Obligatoire',
    invalidEmail: 'Utilisez un email valide',
    invalidPhone: 'Utilisez un numero de telephone valide',
    fixFields: 'Veuillez corriger les champs marques.',
    sentInfo: 'Informations envoyees a PBxcom.',
    reference: 'Reference',
    settingsEyebrow: 'Parametres client',
    settingsTitle: 'Parametres du compte',
    settingsDescription: 'Modifiez vos informations, votre code et votre langue preferee.',
    profileCard: 'Informations du profil',
    fullName: 'Nom complet',
    company: 'Societe',
    email: 'Email',
    passwordCard: 'Code de securite',
    newPassword: 'Nouveau code / mot de passe',
    leaveBlank: 'Laissez vide pour garder le code actuel.',
    languageCard: 'Langue',
    preferredLanguage: 'Langue preferee',
    saveSettings: 'Enregistrer',
    settingsSaved: 'Parametres mis a jour.',
  },
  ar: {
    informationForm: 'استمارة المعلومات',
    ticketHistory: 'سجل التذاكر',
    newTicket: 'تذكرة جديدة',
    settings: 'الإعدادات',
    supportTitle: 'دعم PBxcom',
    supportText: 'راجع طلباتك أو أنشئ تذكرة دعم جديدة.',
    clientInfoEyebrow: 'معلومات العميل',
    clientInfoTitle: 'إنشاء تذكرة جديدة',
    clientInfoDescription: 'تم اقتراح آخر معلومات عميل لك أدناه. يمكنك تعديل أي خانة قبل إرسال التذكرة.',
    firstTicketTitle: 'أكمل أول تذكرة',
    firstTicketDescription: 'املأ كل خانات العميل مرة واحدة. بعد ذلك سيتم قفل معلوماتك في التذاكر القادمة.',
    lockedClientFields: 'هذه المعلومات مأخوذة من حسابك ولا يمكن تعديلها في هذه التذكرة.',
    savedClientFields: 'تم ملء هذه الخانات من آخر تذكرة لك ويمكنك تعديلها قبل الإرسال.',
    chooseCity: 'اختر المدينة',
    backToHistory: 'العودة إلى السجل',
    nom: 'الاسم العائلي',
    prenom: 'الاسم الشخصي',
    societes: 'الشركة',
    nMarche: 'رقم الصفقة',
    nFacture: 'رقم الفاتورة',
    telephone: 'رقم الهاتف',
    mail: 'البريد الإلكتروني',
    ville: 'المدينة',
    problemDescription: 'وصف المشكلة',
    problemDescriptionPlaceholder: 'صف مشكلتك هنا بكل التفاصيل التي تحتاجها.',
    submitInformation: 'إرسال المعلومات',
    required: 'مطلوب',
    invalidEmail: 'أدخل بريدا إلكترونيا صحيحا',
    invalidPhone: 'أدخل رقم هاتف صحيحا',
    fixFields: 'يرجى تصحيح الحقول المحددة.',
    sentInfo: 'تم إرسال المعلومات إلى PBxcom.',
    reference: 'المرجع',
    settingsEyebrow: 'إعدادات العميل',
    settingsTitle: 'إعدادات الحساب',
    settingsDescription: 'قم بتحديث معلومات الحساب والرمز واللغة المفضلة.',
    profileCard: 'معلومات الحساب',
    fullName: 'الاسم الكامل',
    company: 'الشركة',
    email: 'البريد الإلكتروني',
    passwordCard: 'رمز الأمان',
    newPassword: 'رمز / كلمة مرور جديدة',
    leaveBlank: 'اتركه فارغا للاحتفاظ بالرمز الحالي.',
    languageCard: 'اللغة',
    preferredLanguage: 'اللغة المفضلة',
    saveSettings: 'حفظ الإعدادات',
    settingsSaved: 'تم تحديث الإعدادات بنجاح.',
  },
}

export const useLanguageStore = create(
  persist(
    (set) => ({
      language: 'en',
      setLanguage: (language) => set({ language }),
    }),
    { name: 'pbxcom-language' },
  ),
)

export function useTranslation() {
  const language = useLanguageStore((state) => state.language)
  return {
    language,
    t: messages[language] ?? messages.en,
  }
}

export function useLanguageBootstrap() {
  const language = useLanguageStore((state) => state.language)

  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
  }, [language])
}
